### ISSUE TITLE
BASIC runtime checklist

### ISSUE THREAD

**Issue by rynomad** [getfilament/throwback#17]
This is a NON_COMPLETE list of semantics that need to be enforced in order to make throwback more usable. even when this list is completed, a more holistic solution will be built, but this gets us to supporting a truly workable programming environment.

- [ ] Precedence
   - [ ] inline functions and parentheticals evaluations
   - [ ] dot and bracket object accessors
- [ ] Operators
   - [ ] '+' addition and string concatenation
   - [ ] '==' numerical and string eval
   - [ ] '++,--' operate on reference
   - [ ] '>,<,<=,>=' work on DECIMALS
   - [ ] '&&,||,!' logical
- [ ] Kitchen Sink
   - [ ] scripted functions take arguments
   - [ ] newlines lexed and parsed and run correctly

**Comment by rynomad** [comment]
ready to merge pending code review
